#数据源配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        timeout: 5000
#  data:
#    mongodb:
#      uri: mongodb://192.168.5.192/light
#      authentication-database: edu_base
#      username:
#      password:
  datasource:
   url: jdbc:mysql://127.0.0.1:3306/light?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis配置
mybatis:
  type-aliases-package: com.crystal.light.entity
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#pageHelper配置可以不配置
pagehelper:
  propertyName: propertyValue